# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#
# XYZ Utils
#
# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

include: package:lints/recommended.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_renaming_method_parameters: false
    constant_identifier_names: false
    file_names: false
    non_constant_identifier_names: false
    omit_local_variable_types: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_relative_imports: true
    prefer_single_quotes: false
    require_trailing_commas: true
    unnecessary_this: false
    camel_case_types: false
    library_private_types_in_public_api: false
analyzer:
  errors:
    prefer_final_in_for_each: error
    unnecessary_new: error
    use_key_in_widget_constructors: error
    prefer_relative_imports: error
  enable-experiment:
    - variance
    - value-class
    - extension-types
    - const-functions
    - macros
    - inference-update-2
    - records
    - patterns
    - inline-class
    - sealed-class
    - class-modifiers
