//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

library;

export 'all_xyz_utils_web_friendly.g.dart';
export 'src/ansi_styled_string.dart';
export 'src/collection_utils/first_where_or_null.dart';
export 'src/collection_utils/generic_type_extension.dart';
export 'src/collection_utils/jmap.dart';
export 'src/collection_utils/map_filter_extension.dart';
export 'src/collection_utils/mapi.dart';
export 'src/collection_utils/maybe_add_to.dart';
export 'src/collection_utils/merge.dart';
export 'src/collection_utils/misc.dart';
export 'src/collection_utils/non_nulls.dart';
export 'src/collection_utils/null_filtered.dart';
export 'src/collection_utils/var_args.dart';
export 'src/extensions/enum_extensions.dart';
export 'src/extensions/join_with_last_separator_extension.dart';
export 'src/extensions/null_if_empty_extensions.dart';
export 'src/extensions/string_extensions.dart';
export 'src/extensions/to_timmed_or_null_extension.dart';
export 'src/extract_scopes.dart';
export 'src/firestore_timestamp.dart';
export 'src/let.dart';
export 'src/parse_duration.dart';
export 'src/paths.dart';
export 'src/replace_data.dart';
export 'src/string_case_types.dart';
export 'src/type_message_mixin.dart';
export 'src/valid_object.dart';
export 'src/version.dart';
