//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

library;

export 'non_web/all_non_web.g.dart';
export 'non_web/all_xyz_utils_non_web.g.dart';
export 'non_web/src/file_system.dart';
export 'non_web/src/get_package_lib_path.dart';
export 'web_friendly/all_web_friendly.g.dart';
export 'web_friendly/all_xyz_utils_web_friendly.g.dart';
export 'web_friendly/src/ansi_styled_string.dart';
export 'web_friendly/src/collection_utils/generic_type_extension.dart';
export 'web_friendly/src/collection_utils/jmap.dart';
export 'web_friendly/src/collection_utils/map_filter_extension.dart';
export 'web_friendly/src/collection_utils/mapi.dart';
export 'web_friendly/src/collection_utils/maybe_add_to.dart';
export 'web_friendly/src/collection_utils/merge.dart';
export 'web_friendly/src/collection_utils/misc.dart';
export 'web_friendly/src/collection_utils/non_nulls.dart';
export 'web_friendly/src/collection_utils/null_filtered.dart';
export 'web_friendly/src/collection_utils/first_where_or_null.dart';
export 'web_friendly/src/collection_utils/var_args.dart';
export 'web_friendly/src/extensions/enum_extensions.dart';
export 'web_friendly/src/extensions/join_with_last_separator_extension.dart';
export 'web_friendly/src/extensions/null_if_empty_extensions.dart';
export 'web_friendly/src/extensions/string_extensions.dart';
export 'web_friendly/src/extensions/to_timmed_or_null_extension.dart';
export 'web_friendly/src/extract_scopes.dart';
export 'web_friendly/src/firestore_timestamp.dart';
export 'web_friendly/src/let.dart';
export 'web_friendly/src/parse_duration.dart';
export 'web_friendly/src/paths.dart';
export 'web_friendly/src/replace_data.dart';
export 'web_friendly/src/string_case_types.dart';
export 'web_friendly/src/type_message_mixin.dart';
export 'web_friendly/src/valid_object.dart';
export 'web_friendly/src/version.dart';
