//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

export 'web_friendly/any_platform/any_platform.dart';
export 'web_friendly/app/callbacks.dart';
export 'web_friendly/app/collective_service.dart';
export 'web_friendly/app/debouncer.dart';
export 'web_friendly/app/debug_log.dart';
export 'web_friendly/app/disposable_value.dart';
export 'web_friendly/app/function_queue.dart';
export 'web_friendly/app/here.dart';
export 'web_friendly/app/notification_topic.dart';
export 'web_friendly/app/post_destruction_checker.dart';
export 'web_friendly/app/rec.dart';
export 'web_friendly/app/screen_calculator.dart';
export 'web_friendly/app/single_service.dart';
export 'web_friendly/http_service.dart';
export 'web_friendly/patterns/recursive_replace.dart';
export 'web_friendly/patterns/replace_patterns.dart';
export 'web_friendly/second_to_ninth_element_on_iterable_extension.dart';
export 'web_friendly/stream_to_future.dart';
export 'web_friendly/time/date_time.dart';
export 'web_friendly/time/duration_formatted_english.dart';
export 'web_friendly/tuples.dart';
