//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

export 'collections/src/csv.dart';
export 'collections/src/etc.dart';
export 'collections/src/expand_flattened_json.dart';
export 'collections/src/expand_json.dart';
export 'collections/src/first_where_or_null.dart';
export 'collections/src/flatten_json.dart';
export 'collections/src/generic_type_extension.dart';
export 'collections/src/join_with_last_separator_on_iterable_extension.dart';
export 'collections/src/map_filter_extension.dart';
export 'collections/src/map_keys_and_values_on_map_extension.dart';
export 'collections/src/map_to_json.dart';
export 'collections/src/mapi.dart';
export 'collections/src/maybe_add_to.dart';
export 'collections/src/merge.dart';
export 'collections/src/non_nulls_on_map_extension.dart';
export 'collections/src/null_filtered.dart';
export 'collections/src/null_if_empty_extensions.dart';
export 'collections/src/second_to_ninth_element_on_iterable_extension.dart';
export 'collections/src/set_nested_value_on_map_extension.dart';
export 'collections/src/unique_entries.dart';
export 'core/src/ansi_styled_string.dart';
export 'core/src/callbacks.dart';
export 'core/src/debouncer.dart';
export 'core/src/debug_log.dart';
export 'core/src/disposable_value.dart';
export 'core/src/function_queue.dart';
export 'core/src/here.dart';
export 'core/src/let.dart';
export 'core/src/notification_topic.dart';
export 'core/src/paths.dart';
export 'core/src/post_destruction_checker.dart';
export 'core/src/rec.dart';
export 'core/src/screen_calculator.dart';
export 'core/src/try_or_null_on_function_extension.dart';
export 'core/src/type_message_mixin.dart';
export 'core/src/value_of_on_enum_extension.dart';
export 'core/src/version.dart';
export 'experimental/src/chainable.dart';
export 'experimental/src/tuples.dart';
export 'experimental/src/var_args.dart';
export 'http/src/http_service.dart';
export 'http/src/t_http_function_result.dart';
export 'location_utils/src/calculate_best_center_on_location_package_extension.dart';
export 'location_utils/src/calculate_geometric_center_on_location_package_extension.dart';
export 'location_utils/src/calculate_havershire_3d_distance_on_location_package_extension.dart';
export 'location_utils/src/calculate_zoom_to_fit_on_location_package_extension.dart';
export 'location_utils/src/celestial_radius.dart';
export 'location_utils/src/distance_unit.dart';
export 'location_utils/src/location_utils.dart';
export 'location_utils/src/t_location_components.dart';
export 'streams/src/polling_stream.dart';
export 'streams/src/stream_to_future.dart';
export 'streams/src/to_future_on_stream_extension.dart';
export 'string_patterns/src/extract_scopes.dart';
export 'string_patterns/src/recursive_replace.dart';
export 'string_patterns/src/replace_data.dart';
export 'string_patterns/src/replace_patterns.dart';
export 'strings/src/misc_on_string_extension.dart';
export 'strings/src/string_case_conversions_on_string_extension.dart';
export 'strings/src/string_case_types.dart';
export 'strings/src/to_timmed_or_null_on_object_extension.dart';
export 'time/src/date_time.dart';
export 'time/src/duration_formatted_english.dart';
export 'time/src/firestore_timestamp.dart';
export 'time/src/parse_duration_on_string_extension.dart';
