//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

export 'non_web.dart';
export 'shared/all_shared.g.dart';
export 'shared/non_web/all_non_web.g.dart';
export 'shared/non_web/all_xyz_utils_non_web.g.dart';
export 'shared/non_web/src/file_system.dart';
export 'shared/non_web/src/get_package_lib_path.dart';
export 'shared/web_friendly/all_web_friendly.g.dart';
export 'shared/web_friendly/all_xyz_utils_web_friendly.g.dart';
export 'shared/web_friendly/src/ansi_styled_string.dart';
export 'shared/web_friendly/src/collection_utils/first_where_or_null.dart';
export 'shared/web_friendly/src/collection_utils/generic_type_extension.dart';
export 'shared/web_friendly/src/collection_utils/jmap.dart';
export 'shared/web_friendly/src/collection_utils/map_filter_extension.dart';
export 'shared/web_friendly/src/collection_utils/mapi.dart';
export 'shared/web_friendly/src/collection_utils/maybe_add_to.dart';
export 'shared/web_friendly/src/collection_utils/merge.dart';
export 'shared/web_friendly/src/collection_utils/misc.dart';
export 'shared/web_friendly/src/collection_utils/non_nulls.dart';
export 'shared/web_friendly/src/collection_utils/null_filtered.dart';
export 'shared/web_friendly/src/collection_utils/var_args.dart';
export 'shared/web_friendly/src/extensions/enum_extensions.dart';
export 'shared/web_friendly/src/extensions/join_with_last_separator_extension.dart';
export 'shared/web_friendly/src/extensions/null_if_empty_extensions.dart';
export 'shared/web_friendly/src/extensions/string_extensions.dart';
export 'shared/web_friendly/src/extensions/to_timmed_or_null_extension.dart';
export 'shared/web_friendly/src/extract_scopes.dart';
export 'shared/web_friendly/src/firestore_timestamp.dart';
export 'shared/web_friendly/src/let.dart';
export 'shared/web_friendly/src/parse_duration.dart';
export 'shared/web_friendly/src/paths.dart';
export 'shared/web_friendly/src/replace_data.dart';
export 'shared/web_friendly/src/string_case_types.dart';
export 'shared/web_friendly/src/type_message_mixin.dart';
export 'shared/web_friendly/src/valid_object.dart';
export 'shared/web_friendly/src/version.dart';
export 'web_friendly.dart';
export 'web_friendly/all_web_friendly.g.dart';
export 'web_friendly/any_platform/any_platform.dart';
export 'web_friendly/app/callbacks.dart';
export 'web_friendly/app/collective_service.dart';
export 'web_friendly/app/debouncer.dart';
export 'web_friendly/app/debug_log.dart';
export 'web_friendly/app/disposable_value.dart';
export 'web_friendly/app/function_queue.dart';
export 'web_friendly/app/here.dart';
export 'web_friendly/app/notification_topic.dart';
export 'web_friendly/app/post_destruction_checker.dart';
export 'web_friendly/app/rec.dart';
export 'web_friendly/app/screen_calculator.dart';
export 'web_friendly/app/single_service.dart';
export 'web_friendly/http_service.dart';
export 'web_friendly/patterns/replace_patterns.dart';
export 'web_friendly/second_to_ninth_element.dart';
export 'web_friendly/stream_to_future.dart';
export 'web_friendly/time/date_time.dart';
export 'web_friendly/time/duration_formatted_english.dart';
export 'web_friendly/tuples.dart';
export 'xyz_utils.dart';
