//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

export 'non_web/file_system.dart';
export 'non_web/get_package_lib_path.dart';
export 'web_friendly/ansi_styled_string.dart';
export 'web_friendly/collection_utils/expand_flattened_json.dart';
export 'web_friendly/collection_utils/first_where_or_null.dart';
export 'web_friendly/collection_utils/flatten_json.dart';
export 'web_friendly/collection_utils/generic_type_extension.dart';
export 'web_friendly/collection_utils/map_filter_extension.dart';
export 'web_friendly/collection_utils/map_to_json.dart';
export 'web_friendly/collection_utils/mapi.dart';
export 'web_friendly/collection_utils/maybe_add_to.dart';
export 'web_friendly/collection_utils/merge.dart';
export 'web_friendly/collection_utils/more_collection_utils.dart';
export 'web_friendly/collection_utils/non_nulls.dart';
export 'web_friendly/collection_utils/null_filtered.dart';
export 'web_friendly/collection_utils/var_args.dart';
export 'web_friendly/extensions/enum_extensions.dart';
export 'web_friendly/extensions/join_with_last_separator_extension.dart';
export 'web_friendly/extensions/null_if_empty_extensions.dart';
export 'web_friendly/extensions/split_by_last_occurence_of.dart';
export 'web_friendly/extensions/string_extensions.dart';
export 'web_friendly/extensions/to_timmed_or_null_extension.dart';
export 'web_friendly/extract_scopes.dart';
export 'web_friendly/firestore_timestamp.dart';
export 'web_friendly/let.dart';
export 'web_friendly/parse_duration.dart';
export 'web_friendly/paths.dart';
export 'web_friendly/replace_data.dart';
export 'web_friendly/string_case_types.dart';
export 'web_friendly/type_message_mixin.dart';
export 'web_friendly/valid_object.dart';
export 'web_friendly/version.dart';
